const KeyEvent = @import("../ui/terminal.zig").KeyEvent;

pub const Command = enum {
    save,
    quit,
    copy,
    cut,
    paste,
    show_palette,
    goto_line,
    regex_search,
    toggle_comment,
    move_left,
    move_right,
    move_up,
    move_down,
    move_home,
    move_end,
    page_up,
    page_down,
    select_left,
    select_right,
    select_up,
    select_down,
    select_home,
    select_end,
    select_page_up,
    select_page_down,
    block_select_left,
    block_select_right,
    block_select_up,
    block_select_down,
    word_left,
    word_right,
    backspace,
    delete_char,
    insert_newline,
    undo,
    redo,
    lsp_completion,
    lsp_hover,
    lsp_definition,
    lsp_references,
    lsp_jump_back,
};

pub fn mapEditor(event: KeyEvent) ?Command {
    return switch (event) {
        .left => .move_left,
        .right => .move_right,
        .up => .move_up,
        .down => .move_down,
        .home => .move_home,
        .end => .move_end,
        .page_up => .page_up,
        .page_down => .page_down,
        .shift_left => .select_left,
        .shift_right => .select_right,
        .shift_up => .select_up,
        .shift_down => .select_down,
        .shift_home => .select_home,
        .shift_end => .select_end,
        .shift_page_up => .select_page_up,
        .shift_page_down => .select_page_down,
        .alt_left => .block_select_left,
        .alt_right => .block_select_right,
        .alt_up => .block_select_up,
        .alt_down => .block_select_down,
        .word_left => .word_left,
        .word_right => .word_right,
        .backspace => .backspace,
        .delete => .delete_char,
        .enter => .insert_newline,
        .ctrl => |ch| switch (ch) {
            'q' => .quit,
            'x' => .quit,
            'c' => .copy,
            'v' => .paste,
            'k' => .cut,
            's' => .save,
            'p' => .show_palette,
            'g' => .goto_line,
            'f' => .regex_search,
            '/' => .toggle_comment,
            'z' => .undo,
            'y' => .redo,
            'n' => .lsp_completion,
            't' => .lsp_hover,
            'd' => .lsp_definition,
            'r' => .lsp_references,
            'o' => .lsp_jump_back,
            'b' => .move_left,
            'a' => .move_home,
            'e' => .move_end,
            else => null,
        },
        else => null,
    };
}
